### ISSUE TITLE
Não consegui escrever os estados com acentuação

### ISSUE THREAD

**Issue by luizgmelo** [carol-andradech/brasil-states#1]
Quando fui digitar os estados com acentuação ela espacava sempre , exemplo: (S~ao Paulo)

**Comment by carol-andradech** [comment]
Obrigada pelo report. 
Eu testei aqui e funciona normal.
Verifique por favor a sua versão do Python, a partir do Python 3, o encoding padrão é UTF-8.

**Comment by luizgmelo** [comment]
Tentei com o python 3.11.0 e não consegui
